# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brute_force.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import os
import sys

class brute_force_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(534, 189)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 521, 181))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.url_lineEdit = QtWidgets.QLineEdit(self.page)
        self.url_lineEdit.setGeometry(QtCore.QRect(120, 10, 251, 31))
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.char_set_lineEdit = QtWidgets.QLineEdit(self.page)
        self.char_set_lineEdit.setGeometry(QtCore.QRect(120, 50, 251, 31))
        self.char_set_lineEdit.setObjectName("char_set_lineEdit")
        self.min_length_lineEdit = QtWidgets.QLineEdit(self.page)
        self.min_length_lineEdit.setGeometry(QtCore.QRect(10, 90, 141, 31))
        self.min_length_lineEdit.setObjectName("min_length_lineEdit")
        self.max_length_lineEdit = QtWidgets.QLineEdit(self.page)
        self.max_length_lineEdit.setGeometry(QtCore.QRect(10, 130, 141, 31))
        self.max_length_lineEdit.setObjectName("max_length_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(160, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(160, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.page)
        self.comboBox.setGeometry(QtCore.QRect(380, 10, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setGeometry(QtCore.QRect(310, 90, 101, 21))
        self.checkBox.setObjectName("checkBox")
        self.log_file_lineEdit = QtWidgets.QLineEdit(self.page)
        self.log_file_lineEdit.setGeometry(QtCore.QRect(390, 90, 81, 31))
        self.log_file_lineEdit.setObjectName("log_file_lineEdit")
        self.next_btn = QtWidgets.QPushButton(self.page)
        self.next_btn.setGeometry(QtCore.QRect(312, 130, 201, 31))
        self.next_btn.setObjectName("next_btn")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.back_btn = QtWidgets.QPushButton(self.page_2)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.back_btn.setObjectName("back_btn")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.success_message_lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.success_message_lineEdit.setGeometry(QtCore.QRect(10, 90, 181, 31))
        self.success_message_lineEdit.setObjectName("success_message_lineEdit")
        self.headers_lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.headers_lineEdit.setGeometry(QtCore.QRect(120, 130, 271, 31))
        self.headers_lineEdit.setObjectName("headers_lineEdit")
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setGeometry(QtCore.QRect(200, 40, 141, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.cookies_key_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.cookies_key_lineEdit.setGeometry(QtCore.QRect(0, 50, 131, 31))
        self.cookies_key_lineEdit.setObjectName("cookies_key_lineEdit")
        self.final_btn = QtWidgets.QPushButton(self.page_2)
        self.final_btn.setGeometry(QtCore.QRect(400, 130, 121, 31))
        self.final_btn.setObjectName("final_btn")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(340, 40, 171, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.password_param_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.password_param_lineEdit.setGeometry(QtCore.QRect(0, 50, 161, 31))
        self.password_param_lineEdit.setObjectName("password_param_lineEdit")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.start_btn = QtWidgets.QPushButton(self.page_3)
        self.start_btn.setGeometry(QtCore.QRect(420, 130, 101, 31))
        self.start_btn.setObjectName("start_btn")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_12.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 71, 21))
        self.label_13.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(300, 20, 71, 21))
        self.label_14.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(300, 50, 71, 21))
        self.label_15.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(10, 140, 131, 21))
        self.label_19.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setGeometry(QtCore.QRect(300, 80, 131, 21))
        self.label_20.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(300, 100, 131, 21))
        self.label_16.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(450, 20, 71, 21))
        self.label_17.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.url_label = QtWidgets.QLabel(self.page_3)
        self.url_label.setGeometry(QtCore.QRect(90, 20, 191, 21))
        self.url_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.url_label.setAlignment(QtCore.Qt.AlignCenter)
        self.url_label.setObjectName("url_label")
        self.min_len_label = QtWidgets.QLabel(self.page_3)
        self.min_len_label.setGeometry(QtCore.QRect(90, 50, 191, 21))
        self.min_len_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.min_len_label.setAlignment(QtCore.Qt.AlignCenter)
        self.min_len_label.setObjectName("min_len_label")
        self.max_len_label = QtWidgets.QLabel(self.page_3)
        self.max_len_label.setGeometry(QtCore.QRect(90, 70, 191, 21))
        self.max_len_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.max_len_label.setAlignment(QtCore.Qt.AlignCenter)
        self.max_len_label.setObjectName("max_len_label")
        self.char_set_label = QtWidgets.QLabel(self.page_3)
        self.char_set_label.setGeometry(QtCore.QRect(90, 110, 191, 21))
        self.char_set_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.char_set_label.setAlignment(QtCore.Qt.AlignCenter)
        self.char_set_label.setObjectName("char_set_label")
        self.success_label = QtWidgets.QLabel(self.page_3)
        self.success_label.setGeometry(QtCore.QRect(150, 140, 131, 21))
        self.success_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.success_label.setAlignment(QtCore.Qt.AlignCenter)
        self.success_label.setObjectName("success_label")
        self.method_label = QtWidgets.QLabel(self.page_3)
        self.method_label.setGeometry(QtCore.QRect(380, 20, 61, 21))
        self.method_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.method_label.setAlignment(QtCore.Qt.AlignCenter)
        self.method_label.setObjectName("method_label")
        self.headers_label = QtWidgets.QLabel(self.page_3)
        self.headers_label.setGeometry(QtCore.QRect(380, 50, 61, 21))
        self.headers_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.headers_label.setAlignment(QtCore.Qt.AlignCenter)
        self.headers_label.setObjectName("headers_label")
        self.log_file_label = QtWidgets.QLabel(self.page_3)
        self.log_file_label.setGeometry(QtCore.QRect(450, 40, 71, 21))
        self.log_file_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.log_file_label.setAlignment(QtCore.Qt.AlignCenter)
        self.log_file_label.setObjectName("log_file_label")
        self.param_label = QtWidgets.QLabel(self.page_3)
        self.param_label.setGeometry(QtCore.QRect(440, 80, 81, 21))
        self.param_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.param_label.setAlignment(QtCore.Qt.AlignCenter)
        self.param_label.setObjectName("param_label")
        self.cookies_label = QtWidgets.QLabel(self.page_3)
        self.cookies_label.setGeometry(QtCore.QRect(440, 100, 81, 21))
        self.cookies_label.setStyleSheet("QLabel {\n"
"    /*background-color: blue;*/\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.cookies_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cookies_label.setObjectName("cookies_label")
        self.back_btn2 = QtWidgets.QPushButton(self.page_3)
        self.back_btn2.setGeometry(QtCore.QRect(300, 130, 101, 31))
        self.back_btn2.setObjectName("back_btn2")
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setGeometry(QtCore.QRect(450, 20, 71, 41))
        self.label_18.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.stackedWidget.addWidget(self.page_3)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
# =============================================================
        if getattr(sys, 'frozen', False):
                base_path = sys._MEIPASS
        else:
                base_path = os.path.abspath(os.path.dirname(__file__))
        
        icon_path = os.path.join(base_path, "ppimppie_icon.ico")

    # 아이콘 객체를 한 번만 생성
        icon = QIcon(icon_path)
    
    # 애플리케이션과 폼 모두에 아이콘 설정
        app = QtWidgets.QApplication.instance()
        if app:
                app.setWindowIcon(icon)
# =============================================================
        Form.setWindowTitle(_translate("Form", "PpimPpie_Brute_Force"))
        Form.setWindowIcon(icon)        
        self.label.setText(_translate("Form", "URL"))
        self.label_2.setText(_translate("Form", "Char_set"))
        self.label_3.setText(_translate("Form", "Min_length: "))
        self.label_4.setText(_translate("Form", "Max_length: "))
        self.comboBox.setItemText(0, _translate("Form", "GET"))
        self.comboBox.setItemText(1, _translate("Form", "POST"))
        self.comboBox.setItemText(2, _translate("Form", "COOKIE"))
        self.checkBox.setText(_translate("Form", "Log_file"))
        self.next_btn.setText(_translate("Form", "next"))
        self.back_btn.setText(_translate("Form", "Undo"))
        self.label_6.setText(_translate("Form", "Success_message"))
        self.label_8.setText(_translate("Form", "Cookies_key"))
        self.final_btn.setText(_translate("Form", "START"))
        self.label_9.setText(_translate("Form", "password_param"))
        self.label_10.setText(_translate("Form", "Headers"))
        self.start_btn.setText(_translate("Form", "Try"))
        self.label_7.setText(_translate("Form", "URL"))
        self.label_11.setText(_translate("Form", "Min_len"))
        self.label_12.setText(_translate("Form", "Max_len"))
        self.label_13.setText(_translate("Form", "Char_set"))
        self.label_14.setText(_translate("Form", "Method"))
        self.label_15.setText(_translate("Form", "Headers"))
        self.label_19.setText(_translate("Form", "Success_message"))
        self.label_20.setText(_translate("Form", "password_param"))
        self.label_16.setText(_translate("Form", "Cookies_key"))
        self.label_17.setText(_translate("Form", "Log_file"))
        self.url_label.setText(_translate("Form", "URL"))
        self.min_len_label.setText(_translate("Form", "URL"))
        self.max_len_label.setText(_translate("Form", "URL"))
        self.char_set_label.setText(_translate("Form", "URL"))
        self.success_label.setText(_translate("Form", "URL"))
        self.method_label.setText(_translate("Form", "URL"))
        self.headers_label.setText(_translate("Form", "URL"))
        self.log_file_label.setText(_translate("Form", "URL"))
        self.param_label.setText(_translate("Form", "URL"))
        self.cookies_label.setText(_translate("Form", "URL"))
        self.back_btn2.setText(_translate("Form", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
