# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dos_Attack.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import os
import sys

class Dosat_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 545)
        Form.setStyleSheet("")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 551, 91))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pod_btn = QtWidgets.QPushButton(Form)
        self.pod_btn.setGeometry(QtCore.QRect(120, 230, 331, 54))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pod_btn.setFont(font)
        self.pod_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(128, 128, 128, 180);\n"
"    border: 2px solid #2d2d2d;\n"
"    font: 14pt \"Berlin Sans FB\";\n"
"    color: white;\n"
"    padding: 5px;\n"
"    min-height: 40px;\n"
"    max-width: 400px;\n"
"}\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.pod_btn.setObjectName("pod_btn")
        self.la_btn = QtWidgets.QPushButton(Form)
        self.la_btn.setGeometry(QtCore.QRect(120, 300, 331, 54))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.la_btn.setFont(font)
        self.la_btn.setStyleSheet("QPushButton {\n"
"    font: 14pt \"Berlin Sans FB\";\n"
"    background-color: rgba(128, 128, 128, 180);\n"
"    border: 2px solid #2d2d2d;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    min-height: 40px;\n"
"    max-width: 400px;\n"
"}\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.la_btn.setObjectName("la_btn")
        self.synf_btn = QtWidgets.QPushButton(Form)
        self.synf_btn.setGeometry(QtCore.QRect(120, 370, 331, 54))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.synf_btn.setFont(font)
        self.synf_btn.setStyleSheet("QPushButton {\n"
"    font: 14pt \"Berlin Sans FB\";\n"
"    background-color: rgba(128, 128, 128, 180);\n"
"    border: 2px solid #2d2d2d;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    min-height: 40px;\n"
"    max-width: 400px;\n"
"}\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.synf_btn.setObjectName("synf_btn")
        self.s_btn = QtWidgets.QPushButton(Form)
        self.s_btn.setGeometry(QtCore.QRect(120, 440, 331, 54))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.s_btn.setFont(font)
        self.s_btn.setStyleSheet("QPushButton {\n"
"    font: 14pt \"Berlin Sans FB\";\n"
"    background-color: rgba(128, 128, 128, 180);\n"
"    border: 2px solid #2d2d2d;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    min-height: 40px;\n"
"    max-width: 400px;\n"
"}\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.s_btn.setObjectName("s_btn")
        self.d_btn = QtWidgets.QPushButton(Form)
        self.d_btn.setGeometry(QtCore.QRect(120, 130, 331, 54))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.d_btn.setFont(font)
        self.d_btn.setStyleSheet("QPushButton {\n"
"    font: 14pt \"Berlin Sans FB\";\n"
"    background-color: rgba(128, 128, 128, 180);\n"
"    border: 2px solid #2d2d2d;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    min-height: 40px;\n"
"    max-width: 400px;\n"
"}\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.d_btn.setObjectName("d_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
# =============================================================
        if getattr(sys, 'frozen', False):
                base_path = sys._MEIPASS
        else:
                base_path = os.path.abspath(os.path.dirname(__file__))
        
        icon_path = os.path.join(base_path, "ppimppie_icon.ico")

    # 아이콘 객체를 한 번만 생성
        icon = QIcon(icon_path)
    
    # 애플리케이션과 폼 모두에 아이콘 설정
        app = QtWidgets.QApplication.instance()
        if app:
                app.setWindowIcon(icon)
# =============================================================
        Form.setWindowTitle(_translate("Form", "PpimPpie_DoS"))
        Form.setWindowIcon(icon)        
        self.label_4.setText(_translate("Form", "DOS ATTACK"))
        self.pod_btn.setText(_translate("Form", "Ping of death"))
        self.la_btn.setText(_translate("Form", "Land Attack"))
        self.synf_btn.setText(_translate("Form", "SYN Flooding"))
        self.s_btn.setText(_translate("Form", "Smurf"))
        self.d_btn.setText(_translate("Form", "DOS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
