# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dos_fdsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import os
import sys
class Dos_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(335, 234)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 311, 221))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.next_btn = QtWidgets.QPushButton(self.page)
        self.next_btn.setGeometry(QtCore.QRect(210, 190, 91, 20))
        self.next_btn.setObjectName("next_btn")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 140, 171, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 60, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_1.setGeometry(QtCore.QRect(100, 20, 171, 31))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 81, 31))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.label.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 100, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_24 = QtWidgets.QLabel(self.page)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 64, 15))
        self.label_24.setObjectName("label_24")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 311, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.stop_btn = QtWidgets.QPushButton(self.page_2)
        self.stop_btn.setGeometry(QtCore.QRect(10, 180, 281, 28))
        self.stop_btn.setObjectName("stop_btn")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 81, 31))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(0, 50, 81, 31))
        self.label_6.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(0, 90, 91, 31))
        self.label_7.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(0, 130, 121, 31))
        self.label_8.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(0, 160, 121, 31))
        self.label_9.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 20, 171, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 50, 171, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 90, 171, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 130, 151, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 160, 151, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.attack_btn = QtWidgets.QPushButton(self.page_3)
        self.attack_btn.setGeometry(QtCore.QRect(202, 190, 101, 21))
        self.attack_btn.setObjectName("attack_btn")
        self.label_26 = QtWidgets.QLabel(self.page_3)
        self.label_26.setGeometry(QtCore.QRect(0, 0, 81, 16))
        self.label_26.setObjectName("label_26")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.label_10.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.label_11.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_4)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 91, 31))
        self.label_12.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 91, 31))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 20, 171, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 60, 171, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 100, 171, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_13.setGeometry(QtCore.QRect(110, 140, 171, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.attack_btn_2 = QtWidgets.QPushButton(self.page_4)
        self.attack_btn_2.setGeometry(QtCore.QRect(200, 190, 101, 21))
        self.attack_btn_2.setObjectName("attack_btn_2")
        self.label_23 = QtWidgets.QLabel(self.page_4)
        self.label_23.setGeometry(QtCore.QRect(0, 0, 64, 15))
        self.label_23.setObjectName("label_23")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_14 = QtWidgets.QLabel(self.page_5)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.label_15.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_5)
        self.label_16.setGeometry(QtCore.QRect(10, 100, 91, 31))
        self.label_16.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_5)
        self.label_17.setGeometry(QtCore.QRect(10, 140, 91, 31))
        self.label_17.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(110, 20, 171, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(110, 60, 171, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_16.setGeometry(QtCore.QRect(110, 100, 171, 31))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(110, 140, 171, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.attack_btn_3 = QtWidgets.QPushButton(self.page_5)
        self.attack_btn_3.setGeometry(QtCore.QRect(200, 190, 101, 21))
        self.attack_btn_3.setObjectName("attack_btn_3")
        self.label_25 = QtWidgets.QLabel(self.page_5)
        self.label_25.setGeometry(QtCore.QRect(0, 0, 64, 15))
        self.label_25.setObjectName("label_25")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_18 = QtWidgets.QLabel(self.page_6)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.label_18.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_6)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 91, 31))
        self.label_19.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_6)
        self.label_20.setGeometry(QtCore.QRect(10, 130, 91, 31))
        self.label_20.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_18.setGeometry(QtCore.QRect(110, 30, 171, 31))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(110, 80, 171, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_20.setGeometry(QtCore.QRect(110, 130, 171, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.attack_btn_4 = QtWidgets.QPushButton(self.page_6)
        self.attack_btn_4.setGeometry(QtCore.QRect(200, 190, 101, 21))
        self.attack_btn_4.setObjectName("attack_btn_4")
        self.label_22 = QtWidgets.QLabel(self.page_6)
        self.label_22.setGeometry(QtCore.QRect(0, 0, 64, 15))
        self.label_22.setObjectName("label_22")
        self.stackedWidget.addWidget(self.page_6)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
# =============================================================
        if getattr(sys, 'frozen', False):
                base_path = sys._MEIPASS
        else:
                base_path = os.path.abspath(os.path.dirname(__file__))
        
        icon_path = os.path.join(base_path, "ppimppie_icon.ico")

    # 아이콘 객체를 한 번만 생성
        icon = QIcon(icon_path)
    
    # 애플리케이션과 폼 모두에 아이콘 설정
        app = QtWidgets.QApplication.instance()
        if app:
                app.setWindowIcon(icon)
# =============================================================
        Form.setWindowTitle(_translate("Form", "PpimPpie_DoS_Attack"))
        Form.setWindowIcon(icon)        
        self.next_btn.setText(_translate("Form", "attack"))
        self.lineEdit_4.setText(_translate("Form", "44.197.175.168"))
        self.label_4.setText(_translate("Form", "Fake_ip"))
        self.label_3.setText(_translate("Form", "Trd"))
        self.label.setText(_translate("Form", "Target"))
        self.label_2.setText(_translate("Form", "Port"))
        self.label_24.setText(_translate("Form", "DOS"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Doing attack...</p></body></html>"))
        self.stop_btn.setText(_translate("Form", "stop"))
        self.label_5.setText(_translate("Form", "source_ip"))
        self.label_6.setText(_translate("Form", "target_ip"))
        self.label_7.setText(_translate("Form", "message"))
        self.label_8.setText(_translate("Form", "packet_size"))
        self.label_9.setText(_translate("Form", "number_packets"))
        self.lineEdit_7.setText(_translate("Form", "T"))
        self.lineEdit_8.setText(_translate("Form", "60000"))
        self.lineEdit_9.setText(_translate("Form", "5"))
        self.attack_btn.setText(_translate("Form", "attack"))
        self.label_26.setText(_translate("Form", "Ping of death"))
        self.label_10.setText(_translate("Form", "target_ip"))
        self.label_11.setText(_translate("Form", "target_port"))
        self.label_12.setText(_translate("Form", "packets_count"))
        self.label_13.setText(_translate("Form", "delay"))
        self.attack_btn_2.setText(_translate("Form", "attack"))
        self.label_23.setText(_translate("Form", "LAND"))
        self.label_14.setText(_translate("Form", "target_ip"))
        self.label_15.setText(_translate("Form", "target_port"))
        self.label_16.setText(_translate("Form", "packets_count"))
        self.label_17.setText(_translate("Form", "delay"))
        self.attack_btn_3.setText(_translate("Form", "attack"))
        self.label_25.setText(_translate("Form", "SYN"))
        self.label_18.setText(_translate("Form", "source_ip"))
        self.label_19.setText(_translate("Form", "broadcast_ip"))
        self.label_20.setText(_translate("Form", "count"))
        self.attack_btn_4.setText(_translate("Form", "attack"))
        self.label_22.setText(_translate("Form", "SMURF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Dos_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
