# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import os
import sys

class first_loading_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(456, 345)
        Form.setStyleSheet("background-color: #f0f0f0;\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 70, 181, 91))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(180, 220, 101, 28))
        font = QtGui.QFont()
        font.setFamily("궁서")
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("QPushButton {\n"
"        background-color: white;  /* 배경색 흰색 */\n"
"        color: black;             /* 글자색 검정 */\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #f9f9f9;  /* 마우스 올릴 때 연한 회색 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #e6e6e6;  /* 눌렀을 때 더 진한 회색 */\n"
"    }")
        self.btn1.setObjectName("btn1")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(90, 270, 301, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background:white;       /* 배경색 */\n"
"}\n"
"")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate

#         base_path = os.path.abspath(os.path.dirname(__file__))
#         icon_path = os.path.join(base_path, "ppimppie_icon.ico")

#         Form.setWindowTitle(_translate("Form", "PpimPpie_Demo.ver"))
#         Form.setWindowIcon(QIcon(icon_path))  # 동적으로 설정된 경로 사용
#         self.label.setText(_translate("Form", "삠삐"))
#         self.btn1.setText(_translate("Form", "시작하기"))
#         print(icon_path)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
    
        if getattr(sys, 'frozen', False):
                base_path = sys._MEIPASS
        else:
                base_path = os.path.abspath(os.path.dirname(__file__))
        
        icon_path = os.path.join(base_path, "ppimppie_icon.ico")

    # 아이콘 객체를 한 번만 생성
        icon = QIcon(icon_path)
    
    # 애플리케이션과 폼 모두에 아이콘 설정
        app = QtWidgets.QApplication.instance()
        if app:
                app.setWindowIcon(icon)
    
        Form.setWindowTitle(_translate("Form", "1.0.0_ver"))
        Form.setWindowIcon(icon)
        self.label.setText(_translate("Form", "삠삐"))
        self.btn1.setText(_translate("Form", "시작하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = first_loading_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
