# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import os
import sys


class Key_input_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 187)
        Form.setStyleSheet("background-color: #f0f0f0")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 80, 251, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("궁서")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn2 = QtWidgets.QPushButton(Form)
        self.btn2.setGeometry(QtCore.QRect(130, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(11)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.btn2.setObjectName("btn2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
# =============================================================
        if getattr(sys, 'frozen', False):
                base_path = sys._MEIPASS
        else:
                base_path = os.path.abspath(os.path.dirname(__file__))
        
        icon_path = os.path.join(base_path, "ppimppie_icon.ico")

    # 아이콘 객체를 한 번만 생성
        icon = QIcon(icon_path)
    
    # 애플리케이션과 폼 모두에 아이콘 설정
        app = QtWidgets.QApplication.instance()
        if app:
                app.setWindowIcon(icon)
# =============================================================
        Form.setWindowTitle(_translate("Form", "PpimPpie_Check_Key"))
        Form.setWindowIcon(icon)
        self.label.setText(_translate("Form", "인증 키 입력"))
        self.btn2.setText(_translate("Form", "인증 키 입력"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
