# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppimppie_title.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import os
import sys

class ppimppie_title_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(637, 609)
        Form.setStyleSheet("background-color: #f0f0f0")
        self.befo_btn = QtWidgets.QPushButton(Form)
        self.befo_btn.setGeometry(QtCore.QRect(120, 170, 391, 39))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.befo_btn.setFont(font)
        self.befo_btn.setStyleSheet("QPushButton {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid white;\n"
"    color: black;\n"
"    padding: 5px;\n"
"    min-height: 25px;\n"
"    max-width: 400px;\n"
"}\n"
"\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.befo_btn.setObjectName("befo_btn")
        self.dos_btn = QtWidgets.QPushButton(Form)
        self.dos_btn.setGeometry(QtCore.QRect(120, 220, 391, 39))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dos_btn.setFont(font)
        self.dos_btn.setStyleSheet("QPushButton {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid white;\n"
"    color: black;\n"
"    padding: 5px;\n"
"    min-height: 25px;\n"
"    max-width: 400px;\n"
"    font-family: Arial;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.dos_btn.setObjectName("dos_btn")
        self.w_shall_btn = QtWidgets.QPushButton(Form)
        self.w_shall_btn.setGeometry(QtCore.QRect(120, 270, 391, 39))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.w_shall_btn.setFont(font)
        self.w_shall_btn.setStyleSheet("QPushButton {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid white;\n"
"    color: black;\n"
"    padding: 5px;\n"
"    min-height: 25px;\n"
"    max-width: 400px;\n"
"    font-family: Arial;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.w_shall_btn.setObjectName("w_shall_btn")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 320, 391, 39))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid white;\n"
"    color: black;\n"
"    padding: 5px;\n"
"    min-height: 25px;\n"
"    max-width: 400px;\n"
"    font-family: Arial;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 410, 191, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid white;\n"
"    color: black;\n"
"    padding: 5px;\n"
"    min-height: 25px;\n"
"    max-width: 400px;\n"
"    font-family: Arial;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(220, 460, 191, 41))
        self.exit_btn.setStyleSheet("QPushButton {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid white;\n"
"    color: black;\n"
"    padding: 5px;\n"
"    min-height: 25px;\n"
"    max-width: 400px;\n"
"    font-family: Arial;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"/* 버튼에 마우스를 올렸을 때 */\n"
"QPushButton:hover {\n"
"    background-color: #dee2e6;\n"
"    border: 2px solid #0000ff;\n"
"}\n"
"\n"
"/* 버튼을 클릭했을 때 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(98, 98, 98, 180);\n"
"}")
        self.exit_btn.setObjectName("exit_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 570, 221, 16))
        self.label.setStyleSheet("QLabel {\n"
"    color: black;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(380, 580, 241, 20))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: black;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(190, 50, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: blue;\n"
"    border: 1px solid blue;\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(220, 120, 191, 16))
        font = QtGui.QFont()
        font.setFamily("휴먼옛체")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"/*    background-color: black; */\n"
"    color: yellow;\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 590, 221, 16))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
# =============================================================
        if getattr(sys, 'frozen', False):
                base_path = sys._MEIPASS
        else:
                base_path = os.path.abspath(os.path.dirname(__file__))
        
        icon_path = os.path.join(base_path, "ppimppie_icon.ico")

    # 아이콘 객체를 한 번만 생성
        icon = QIcon(icon_path)
    
    # 애플리케이션과 폼 모두에 아이콘 설정
        app = QtWidgets.QApplication.instance()
        if app:
                app.setWindowIcon(icon)
# =============================================================
        Form.setWindowTitle(_translate("Form", "PpimPpie_Title"))
        Form.setWindowIcon(icon)
        self.befo_btn.setText(_translate("Form", "브로트 포스"))
        self.dos_btn.setText(_translate("Form", "도스"))
        self.w_shall_btn.setText(_translate("Form", "웹쉘"))
        self.pushButton_4.setText(_translate("Form", "삠삐 설명서"))
        self.pushButton_5.setText(_translate("Form", "설정"))
        self.exit_btn.setText(_translate("Form", "삠삐 종료"))
        self.label.setText(_translate("Form", "PPimPPie 0.0.0/demo.ver (기능 7(3)개)"))
        self.label_2.setText(_translate("Form", "Copyright Minki PK, Do not distrbute!"))
        self.label_4.setText(_translate("Form", "PPIMPPIE"))
        self.label_3.setText(_translate("Form", "WebToolYee EDITION"))
        self.label_5.setText(_translate("Form", "PPimPPie 1.0.0/tools (기능 7개)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = ppimppie_title_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
