# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Key_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 192)
        Form.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 80, 241, 31))
        self.textEdit.setStyleSheet("QPushButton {\n"
"        background-color: white;  /* 배경색 흰색 */\n"
"        color: black;             /* 글자색 검정 */\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.butn = QtWidgets.QPushButton(Form)
        self.butn.setGeometry(QtCore.QRect(260, 80, 93, 28))
        self.butn.setStyleSheet("QPushButton {\n"
"        background-color: white;  /* 배경색 흰색 */\n"
"        color: black;             /* 글자색 검정 */\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #f9f9f9;  /* 마우스 올릴 때 연한 회색 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #e6e6e6;  /* 눌렀을 때 더 진한 회색 */\n"
"    }")
        self.butn.setObjectName("butn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: black;\n"
"    color: #33FF33;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 80, 241, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.butn.setText(_translate("Form", "submit"))
        self.label.setText(_translate("Form", "Input Your Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
