# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(120, 400, 601, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background: rgb(0, 0, 0);       /* 배경색 */\n"
"}\n"
"")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 130, 631, 121))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.butn = QtWidgets.QPushButton(self.centralwidget)
        self.butn.setGeometry(QtCore.QRect(360, 320, 93, 28))
        self.butn.setStyleSheet("QPushButton {\n"
"        background-color: white;  /* 배경색 흰색 */\n"
"        color: black;             /* 글자색 검정 */\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #f9f9f9;  /* 마우스 올릴 때 연한 회색 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #e6e6e6;  /* 눌렀을 때 더 진한 회색 */\n"
"    }")
        self.butn.setObjectName("butn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Web_Tool_Yee"))
        self.butn.setText(_translate("MainWindow", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
